# User config
author: "Uyen Le"
tagline: ""
description: "uyenle portfolio"
keywords: "uyen le, personal website, portfolio"
email: "hellouyenle@gmail.com"
linkedin: "https://www.linkedin.com/in/uyenle57"
github: "https://github.com/uyenle5796"
behance: "https://behance.net/uyenle"

#Site navigation
about: "About"
illustrations: "Illustrations"
computing: "Computing"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
